# PyTorch
**PyTorch** is a ML and DL framework. It allows you to manipulate and perform operations on data and write ML and DL algorithms

In [2]:
import torch 
from torch import nn
# if already installed
#torch.__version__

Data in ML and DL problems are usually represented in form of **Tensors**. For example a RGB image with width and height 224 pixels could be represented in a tensor of shape [224,224,3]

In [9]:
X = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
X

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

This is a example of a tensor. You can imagine it as nested arrays for better visualization.
These tensors have dimensions,shape and place where it is stored
Shape errors are the most common errors while working with tensors

In [41]:
X.ndim,X.shape,X.device

(3, torch.Size([2, 3, 3]), device(type='cpu'))

This acts like a measure of size for the tensor
-->One way to check dimensions is to count the number of square brackets
![example of different tensor dimensions](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-different-tensor-dimensions.png)


A tensor can be creates using the above used torch.tensor(arg)
-->the arg should be a array-like object

The tensor doesn't change unless reassigned 

## Different ways to create a tensor

In [10]:
# Array of arrays
T1 = torch.tensor([[1,1,1],[2,2,2]])

# Scalar
T2 = torch.tensor(7)

# Numpy array
import numpy as np
A3 = np.array([[1,2,3],[4,5,6]])
T3 = torch.from_numpy(A3)

# Zeroes and Ones 
T4 = torch.zeros(2,3)
T5 = torch.ones(2,3)

# Random tensor
T6 = torch.rand(size=(2,3))

#Creating a tensor in a range
T7 = torch.arange(0,1,0.1)

T1,T2,T3,T4,T5,T6,T7

(tensor([[1, 1, 1],
         [2, 2, 2]]),
 tensor(7),
 tensor([[1, 2, 3],
         [4, 5, 6]], dtype=torch.int32),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0.2274, 0.8546, 0.1826],
         [0.6372, 0.4153, 0.2929]]),
 tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
         0.9000]))

## Indexing
Indexing of tensors are very similiar to lists and nested lists in Python
The indexing goes from outermost array to the innermost array

In [36]:
X = torch.rand(2,3,3)
X

tensor([[[0.4654, 0.1352, 0.2454],
         [0.7015, 0.0752, 0.5946],
         [0.5770, 0.7322, 0.0645]],

        [[0.0491, 0.5258, 0.8134],
         [0.0470, 0.6637, 0.6584],
         [0.9100, 0.9794, 0.3959]]])

In [38]:
# The first number is index of the array and the second nuber is the index of element in that array
X[0],X[0][0],X[0][0][0] #or X[0],X[0,0],X[0,0,0]

(tensor([[0.4654, 0.1352, 0.2454],
         [0.7015, 0.0752, 0.5946],
         [0.5770, 0.7322, 0.0645]]),
 tensor([0.4654, 0.1352, 0.2454]),
 tensor(0.4654))

Sometimes ":" is used to specify all values in that dimension

## Tensor Operations
Arithematic operations can be performed on tensors 
>Addition<br>
>Subtraction<br>
>Multiplication (element-wise)<br>
>Division<br>
>Matrix multiplication<br>

In [43]:
A = torch.rand(3,3)
B = torch.rand(3,3)
A,B

(tensor([[0.0387, 0.1046, 0.6016],
         [0.6386, 0.2815, 0.3608],
         [0.7327, 0.1983, 0.2058]]),
 tensor([[0.0592, 0.7194, 0.1704],
         [0.2114, 0.7615, 0.6456],
         [0.1249, 0.5405, 0.8303]]))

Addition can be performed using the usual "+" operator

In [45]:
A+B,A+10

(tensor([[0.0979, 0.8240, 0.7720],
         [0.8500, 1.0430, 1.0064],
         [0.8576, 0.7388, 1.0361]]),
 tensor([[10.0387, 10.1046, 10.6016],
         [10.6386, 10.2815, 10.3608],
         [10.7327, 10.1983, 10.2058]]))

Same goes for subtraction, multiplication, division
PS: Multiplication here implies element - wise

In [46]:
A-B, A*B, A/B

(tensor([[-0.0205, -0.6148,  0.4312],
         [ 0.4273, -0.4801, -0.2847],
         [ 0.6078, -0.3422, -0.6245]]),
 tensor([[0.0023, 0.0753, 0.1025],
         [0.1350, 0.2144, 0.2330],
         [0.0915, 0.1072, 0.1709]]),
 tensor([[0.6531, 0.1454, 3.5305],
         [3.0214, 0.3696, 0.5590],
         [5.8666, 0.3669, 0.2479]]))

There is a unique operator for matrix multiplication
You either use matmul() or mm() or "@" operator for matrix multiplication

In [48]:
torch.matmul(A,B)

tensor([[0.0995, 0.4327, 0.5736],
        [0.1424, 0.8688, 0.5902],
        [0.1110, 0.7894, 0.4238]])

In [49]:
A@B

tensor([[0.0995, 0.4327, 0.5736],
        [0.1424, 0.8688, 0.5902],
        [0.1110, 0.7894, 0.4238]])

Matrix multiplication using tensors follows the rules of normal matrix multiplication
Eg: (2,2) @ (3,3) is not allowed
    (2,3) @ (3,2) is allowed

Since we are talking about matrices there is a built-in transpose method or torch.tensor(input,dim0,dim1) where dim0 and dim need to be swapped

In [53]:
A.T,B.T

(tensor([[0.0387, 0.6386, 0.7327],
         [0.1046, 0.2815, 0.1983],
         [0.6016, 0.3608, 0.2058]]),
 tensor([[0.0592, 0.2114, 0.1249],
         [0.7194, 0.7615, 0.5405],
         [0.1704, 0.6456, 0.8303]]))

The minimum, maximum, mean and sum of a tensor can be found using built-in methods

In [58]:
A.min(),A.max(),A.mean(),A.sum()

(tensor(0.0387), tensor(0.7327), tensor(0.3514), tensor(3.1627))

The position of min and max element can be found usin argmin() and argmax() methods

## Reshaping, stacking, squeezing and unsqueezing
>torch.reshape(input, shape) -- Reshapes input to shape (if compatible), can also use torch.Tensor.reshape().<br>
torch.Tensor.view(shape) -- Returns a view of the original tensor in a different shape but shares the same data as the original tensor.<br>
torch.stack(tensors, dim=0) -- Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.<br>
torch.squeeze(input) -- Squeezes input to remove all the dimenions with value 1.<br>
torch.unsqueeze(input, dim) -- Returns input with a dimension value of 1 added at dim.<br>
torch.permute(input, dims) -- Returns a view of the original input with its dimensions permuted (rearranged) to dims.<br>

In [7]:
# Defining a tensor
X = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
X,X.shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

torch.reshape(some_tensor,(required_shape))
Return some_tensor in required_shape

In [8]:
X1 = torch.reshape(X,(1,3,3)) # Tensors have to be reassigned
X1

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

This returns the matrix in the given shape 

In [12]:
X.view(1,3,3)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

torch.stack([tensors],dim=n) is used stack tensors of **same size**

In [41]:
Y = torch.tensor([[1,1,1],[2,2,2],[3,3,3]])
torch.stack([X,Y],dim=0)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 1, 1],
         [2, 2, 2],
         [3, 3, 3]]])

torch.squeeze(input)method removes all dimensions with value 1

In [53]:
X2 = torch.squeeze(X)
X1.shape,X2.shape

(torch.Size([1, 3, 3]), torch.Size([3, 3]))

In [58]:
X2.shape,torch.unsqueeze(X2,dim=0)

(torch.Size([3, 3]),
 tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]))

### Thats all for now :)